name: ⚡ Discussion on the performance of Aphrodite
description: Submit a proposal/discussion about the performance of Aphrodite
title: "[Performance]: "
labels: ["performance"]

body:
- type: markdown
  attributes:
    value: >
        #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/PygmalionAI/aphrodite-engine/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: Proposal to improve performance
    description: >
      How do you plan to improve Aphrodite's performance?
  validations:
    required: false
- type: textarea
  attributes:
    label: Report of performance regression
    description: >
      Please provide detailed description of performance comparison to confirm the regression. You may want to run the benchmark script at https://github.com/PygmalionAI/aphrodite-engine/tree/main/tests/benchmarks .
  validations:
    required: false
- type: textarea
  attributes:
    label: Misc discussion on performance
    description: >
      Anything about the performance.
  validations:
    required: false
- type: textarea
  attributes:
    label: Your current environment (if you think it is necessary)
    description: |
      Please run the following and paste the output below.
      ```sh
      wget https://raw.githubusercontent.com/PygmalionAI/aphrodite-engine/main/env.py
      # For security purposes, please check the contents of env.py before running it.
      python env.py
      ```
    value: |
      ```text
      The output of `python env.py`
      ```
  validations:
    required: false
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉~