global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: aphrodite-engine
    metrics_path: /metrics/
    static_configs:
      - targets:
          - 'host.docker.internal:2242'