global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: aphrodite-engine
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - 'sc-arlington-commitments-antarctica.trycloudflare.com'