name: 🐛 Bug report
description: Raise an issue here if you find a bug.
title: "[Bug]: "
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/PygmalionAI/aphrodite-engine/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: Your current environment
    description: |
      Please run the following and paste the output below.
      ```sh
      wget https://raw.githubusercontent.com/PygmalionAI/aphrodite-engine/main/env.py
      # For security purposes, please check the contents of env.py before running it.
      python env.py
      ```
    value: |
      ```text
      The output of `python env.py`
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.
      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:
      ```python
      # All necessary imports at the beginning
      import torch
      # A succinct reproducing example trimmed down to the essential parts:
      t = torch.rand(5, 10)  # Note: the bug is here, we should pass requires_grad=True
      t.sum().backward()
      ```
      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.
      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.
      ```python
      # Sample code to reproduce the problem
      ```
      ```
      Your error message with the FULL traceback.
      ```
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      ⚠️ Please separate bugs of `transformers` implementation or usage from `aphrodite` bugs. If you think anything is wrong with the models' output:
      - Try the same model on transformers. If the issue persists, submit your problem to [their issues](https://github.com/huggingface/transformers/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
      - If the error only appears in Aphrodite, please provide the detailed script of how you run `transformers` and `aphrodite` tests, also highlight the difference and what you expect.
      Thanks for contributing 🎉~