name: 🤗 Support request for a new model architecture from Hugging Face
description: Submit a proposal/request for a new architecture from Hugging Face
title: "[New Model]: "
labels: ["new model"]

body:
- type: markdown
  attributes:
    value: >
        #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/PygmalionAI/aphrodite-engine/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: The model to consider.
    description: >
      A huggingface url, pointing to the model, e.g. https://huggingface.co/openai-community/gpt2 .
  validations:
    required: true
- type: textarea
  attributes:
    label: The closest model Aphrodite already supports.
    description: >
      Here is the list of models already supported by Aphrodite: https://github.com/PygmalionAI/aphrodite-engine/tree/main/aphrodite/modeling/models . Which model is the most similar to the model you want to add support for?
- type: textarea
  attributes:
    label: What's your difficulty of supporting the model you want?
    description: >
      For example, any new operators or unconventional design choices?
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉~